name: Update dynamic assets

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  update-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up asset directory
        run: mkdir -p assets/cards

      - name: Download and update dynamic assets
        run: |
          trophies_url="https://github-profile-trophy.vercel.app"
          stats_url="https://denvercoder1-github-readme-stats.vercel.app"

          declare -A urls=(
            ["trophies-dark"]="${trophies_url}/?username=cycneuramus&rank=-B,-C,-?&column=-1&no-bg=true&theme=gitdimmed"
            ["trophies-light"]="${trophies_url}/?username=cycneuramus&rank=-B,-C,-?&column=-1&no-bg=true"
            ["nmgr-dark"]="${stats_url}/api/pin/?username=cycneuramus&repo=nmgr&theme=github_dark"
            ["nmgr-light"]="${stats_url}/api/pin/?username=cycneuramus&repo=nmgr"
            ["cloudflare-dns-failover-dark"]="${stats_url}/api/pin/?username=cycneuramus&repo=cloudflare-dns-failover&theme=github_dark"
            ["cloudflare-dns-failover-light"]="${stats_url}/api/pin/?username=cycneuramus&repo=cloudflare-dns-failover"
            ["bastille-signalproxy-dark"]="${stats_url}/api/pin/?username=cycneuramus&repo=bastille-signalproxy&theme=github_dark"
            ["bastille-signalproxy-light"]="${stats_url}/api/pin/?username=cycneuramus&repo=bastille-signalproxy"
            ["signal-aichat-dark"]="${stats_url}/api/pin/?username=cycneuramus&repo=signal-aichat&theme=github_dark"
            ["signal-aichat-light"]="${stats_url}/api/pin/?username=cycneuramus&repo=signal-aichat"
            ["homelab-dark"]="${stats_url}/api/pin/?username=cycneuramus&repo=homelab&theme=github_dark"
            ["homelab-light"]="${stats_url}/api/pin/?username=cycneuramus&repo=homelab"
            ["ansible-hybrid-cloud-dark"]="${stats_url}/api/pin/?username=cycneuramus&repo=ansible-hybrid-cloud&theme=github_dark"
            ["ansible-hybrid-cloud-light"]="${stats_url}/api/pin/?username=cycneuramus&repo=ansible-hybrid-cloud"
            ["immich-dark"]="${stats_url}/api/pin/?username=immich-app&repo=immich&theme=github_dark&show_description=false"
            ["immich-light"]="${stats_url}/api/pin/?username=immich-app&repo=immich&show_description=false"
            ["rclone-dark"]="${stats_url}/api/pin/?username=rclone&repo=rclone&theme=github_dark&show_description=false"
            ["rclone-light"]="${stats_url}/api/pin/?username=rclone&repo=rclone&show_description=false"
            ["packages-dark"]="${stats_url}/api/pin/?username=nim-lang&repo=packages&theme=github_dark&show_description=false"
            ["packages-light"]="${stats_url}/api/pin/?username=nim-lang&repo=packages&show_description=false"
            ["seaweedfs-dark"]="${stats_url}/api/pin/?username=seaweedfs&repo=seaweedfs&theme=github_dark&show_description=false"
            ["seaweedfs-light"]="${stats_url}/api/pin/?username=seaweedfs&repo=seaweedfs&show_description=false"
          )

          changed=false

          for name in "${!urls[@]}"; do
            path="assets/cards/${name}.svg"
            tmp="${path}.tmp"

            curl --fail --silent --show-error --location "${urls[$name]}" -o "$tmp" || {
                echo "Failed to fetch ${name} from ${urls[$name]}"
                rm -f "$tmp"
                continue
            }

            if ! grep -q "<svg" "$tmp"; then
              echo "Invalid SVG content for ${name}, skipping."
              rm -f "$tmp"
              continue
            fi

            if [ ! -f "$path" ] || ! cmp -s "$path" "$tmp"; then
              mv "$tmp" "$path"
              git add "$path"
              changed=true
            else
              rm "$tmp"
            fi
          done

          if [ "$changed" = false ]; then
            echo "No asset changes detected."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update dynamic assets"
          git push
